dev-chain: ../bin/geth.sh --ipcdisable --rpc --datadir ../chaindata
test-chain: ../bin/geth.sh --ipcpath ../test-chain.ipc --rpc --rpcport 9545
client: npm run dev
paywall: sleep 2; npm run deploy && npm start
solc: trap exit INT; while true; do (find ../contracts -name '*.sol'; ls ../bin/.solc-colors ../bin/solc-combined.sh) | entr ../bin/solc-combined.sh "contracts/*.sol"; done
